### ISSUE TITLE
Security responses should be reported using exceptions

### ISSUE THREAD

**Issue by martin-sladecek** [oracle/helidon#1185]
It's currently impossible to change the format of 401/403 responses of the security framework (e.g. to a json response with some additional data).

## Environment Details
* Helidon Version: 1.4.0
* Helidon MP
* JDK version: 11.0.5
* OS: Linux
* Docker version (if applicable):

----------

## Problem Description

This is because the response is reported through `ContainerRequestContext.abortWith()`, which is not interceptable. It might be better to use WebApplicationExceptions instead (without a body since otherwise they are not mappable).

## Steps to reproduce
N/A

**Comment by tomas-langer** [comment]
`ContainerResponseFilter` can be used as a solution to resolve cases that were aborted.
The solution with exception allows for better control of entity content, so we will look into it. Maybe not within 1.4 release, but later

**Comment by tomas-langer** [comment]
The behavior could be configurable (e.g. whether to abort or use an exception)

**Comment by tomas-langer** [comment]
The PR adds the following configuration:
 - in `SecurityFeature.Builder`, there is a new method `useAbortWith(boolean)` that can be used to configure use of exceptions rather than aborting the request. Set this to `false` to use exceptions
 - you can also use a configuration option `security.jersey.use-abort-with` for the same purpose (e.g. set it to `false` to use exceptions). 

In Helidon MP, the configuration approach (e.g. `use-abort-with`) would work without additional changes.
In Helidon SE, you need to make sure the `SecurityFeature` is configured correctly.

**Comment by tomas-langer** [comment]
@martin-sladecek could you please have a look at the PR and let me know if this answers your needs?
