### ISSUE TITLE
Basic Quickstart Maven archetype

### ISSUE THREAD

**Issue by m0mus** [oracle/helidon#1239]
We need to have a quickstart Maven archetype for Helidon MP which generates an empty project containing no demo services.

**Comment by romain-grecourt** [comment]
Have you looked at the bare archetype ?

**Comment by m0mus** [comment]
@romain-grecourt No. Can you point me on it?

**Comment by romain-grecourt** [comment]
Here is the command:

```bash
mvn archetype:generate \
    -DinteractiveMode=false  \
    -DarchetypeGroupId=io.helidon.archetypes \
    -DarchetypeArtifactId=helidon-mp \
    -DarchetypeVersion=1.4.0 \
    -DgroupId=com.example \
    -DartifactId=my-app \
    -Dpackage=com.example.myapp \
    -DrestResource=no \
    -DapplicationYaml=no
```

The defaults for `resourceResource` and `applicationYaml` is `yes` ; so by default without overriding these to `no` you get a JAXRS application class, a JAXRS resource class and an application.yaml for Helidon config.

If you set these to no like above you get no JAXRS classes and no application.yaml.

Optional files in Maven archetype isn't really supported, it's do-able using a groovy script that runs post generation to remove the 'optional' files.

There is currently a bug in the script we provide where it doesn't expand the archetype properties in the file names to remove ; i.e optional file names that are static are removed (e.g. Main.java), but the ones that have properties in them aren't (e.g. src/main/java/com/example/myapp/\_\_applicationName\_\_.java).

Unfortunately there is no easy way to test that with the standard maven archetype test harness.

Anyway, here is the fix needed to address this issue:

```diff
diff --git a/archetypes/mp/src/main/resources/META-INF/archetype-post-generate.groovy b/archetypes/mp/src/main/resources/META-INF/archetype-post-generate.groovy
index 462ff8b50..db1c57a7d 100644
--- a/archetypes/mp/src/main/resources/META-INF/archetype-post-generate.groovy
+++ b/archetypes/mp/src/main/resources/META-INF/archetype-post-generate.groovy
@@ -32,7 +32,12 @@ def optionalFiles = [
 // remove optional files that should not be included
 def processOptionalFiles(prop, fnames) {
   if (request.getProperties().get(prop).matches("n|no|false")) {
-    fnames.each{ fname -> new File(fname).delete() }
+    fnames.each{ fname ->
+      request.getProperties().each { entry ->
+        fname = fname.replaceAll("__${entry.key}__","${entry.value}")
+      }
+      new File(fname).delete()
+    }
   }
 }
 optionalFiles.each{ key, value -> processOptionalFiles(key, value) }
diff --git a/archetypes/se/src/main/resources/META-INF/archetype-post-generate.groovy b/archetypes/se/src/main/resources/META-INF/archetype-post-generate.groovy
index 90bbb0c30..ec5bd5e33 100644
--- a/archetypes/se/src/main/resources/META-INF/archetype-post-generate.groovy
+++ b/archetypes/se/src/main/resources/META-INF/archetype-post-generate.groovy
@@ -32,7 +32,12 @@ def optionalFiles = [
 // remove optional files that should not be included
 def processOptionalFiles(prop, fnames) {
   if (request.getProperties().get(prop).matches("n|no|false")) {
-    fnames.each{ fname -> new File(fname).delete() }
+    fnames.each{ fname ->
+      request.getProperties().each { entry ->
+        fname = fname.replaceAll("__${entry.key}__","${entry.value}")
+      }
+      new File(fname).delete()
+    }
   }
 }
```

We should get that fix included in the next 1.x release.
Also note that these 'bare' archetypes are used by some of the guides, but not documented explicitly.

We need to figure out to fit something for them in the docs for 1.x, (not for 2.x since we will have a different project generation tool ) 

/CC @barchetta
