### ISSUE TITLE
Static serving of a webpage does not work correctly

### ISSUE THREAD

**Issue by m0mus** [oracle/helidon#149]
When statically serving a webpage (with index.html + js and other resources), by using the following property:
```
server.static.classpath.context=/ui
```
and having something like this in the index.html
```
<script data-main='require.config' src='./libs/requirejs/require.js'></script>
```
The webpage fails to load when using` http://localhost:7001/ui`, because the relative URIs cannot be resolved correctly in this case. Normally, the webserver should *redirect* this URI to either `http://localhost:7001/ui/` (note the slash at the end) or `http://localhost:7001/ui/index.html`

Reported by Martin Sladecek

**Comment by tomas-langer** [comment]
Fixed by redirecting to /ui/ in case a default page exists and then serving the content.
Also added support for "server.base-path" in MP configuration. 
If base path is configured, the root path will redirect to this path, e.g. 
server.port: 8080
server.host: localhost
server.base-path: /ui/

When you request http://localhost:8080 you get redirected to http://localhost:8080/ui/

Fixed by #144
