### ISSUE TITLE
JAX-RS resources should have implicit Dependent annotation

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#154]
Currently I must annotate a JAX-RS resource with @Path (for JAX-RS) and @RequestScoped or @ApplicationScoped (for CDI).

As these resources are by default request scoped, maybe this should be automatically used for injection.

If I do not annotate the class with neither of Application or Request Scoped annotations, injection is going to fail in HK2 

When debugging, I could see the CDI actually does inject the values correctly, yet HK2 then subsequently fails that it cannot inject them

## Environment Details
* Helidon Version: 0.10.5-SNAPSHOT
* Helidon MP
* JDK version: 8
* OS: Mac

----------

Stack trace:
```
WARNING: The following warnings have been detected: WARNING: Unknown HK2 failure detected:
MultiException stack 1 of 1
org.glassfish.hk2.api.UnsatisfiedDependencyException: There was no object available for injection at SystemInjecteeImpl(requiredType=JsonWebToken,parent=Runner$TheResource,qualifiers={},position=-1,optional=false,self=false,unqualified=null,942306357)
	at org.jvnet.hk2.internal.ThreeThirtyResolver.resolve(ThreeThirtyResolver.java:75)
	at org.jvnet.hk2.internal.Utilities.justInject(Utilities.java:1012)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.inject(ServiceLocatorImpl.java:1008)
	at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.inject(AbstractHk2InjectionManager.java:231)
	at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.inject(ImmediateHk2InjectionManager.java:54)
	at org.glassfish.jersey.ext.cdi1x.internal.AbstractCdiBeanSupplier$2.getInstance(AbstractCdiBeanSupplier.java:112)
	at org.glassfish.jersey.ext.cdi1x.internal.AbstractCdiBeanSupplier._provide(AbstractCdiBeanSupplier.java:127)
	at org.glassfish.jersey.ext.cdi1x.internal.GenericCdiBeanSupplier.get(GenericCdiBeanSupplier.java:66)
	at org.glassfish.jersey.inject.hk2.InstanceSupplierFactoryBridge.provide(InstanceSupplierFactoryBridge.java:77)
	at org.jvnet.hk2.internal.FactoryCreator.create(FactoryCreator.java:153)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
	at org.jvnet.hk2.internal.PerLookupContext.findOrCreate(PerLookupContext.java:70)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:777)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:740)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:710)
	at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.getInstance(AbstractHk2InjectionManager.java:184)
	at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.getInstance(ImmediateHk2InjectionManager.java:54)
	at org.glassfish.jersey.internal.inject.Injections.getOrCreate(Injections.java:129)
	at org.glassfish.jersey.server.model.MethodHandler$ClassBasedMethodHandler.getInstance(MethodHandler.java:284)
	at org.glassfish.jersey.server.internal.routing.PushMethodHandlerRouter.apply(PushMethodHandlerRouter.java:75)
	at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:110)
	at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:113)
	at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:113)
	at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:113)
	at org.glassfish.jersey.server.internal.routing.RoutingStage.apply(RoutingStage.java:93)
	at org.glassfish.jersey.server.internal.routing.RoutingStage.apply(RoutingStage.java:62)
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:197)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:269)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
	at io.helidon.webserver.jersey.JerseySupport$JerseyHandler.lambda$accept$1(JerseySupport.java:207)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ljnelson** [comment]
Some background mostly for other readers who may come across this:

The JAX-RS specification states that a resource class' default lifecycle is per-lookup.  Section 3.1.1 reads:

> By default a new resource class instance is created for each request to that resource. First the constructor (see Section 3.1.2) is called, then any requested dependencies are injected (see Section 3.2), then the appropriate method (see Section 3.3) is invoked and finally the object is made available for garbage collection.

Strictly speaking the CDI scope that matches this exactly is [`Dependent`](http://docs.jboss.org/cdi/api/2.0/javax/enterprise/context/Dependent.html).  However most users would probably expect [`RequestScoped`](http://docs.jboss.org/cdi/api/2.0/javax/enterprise/context/RequestScoped.html) semantics, and just as a point of note this is exactly what, for example, [RestEasy does](http://docs.jboss.org/resteasy/docs/3.6.2.Final/userguide/html/CDI.html#d4e2782).  So in general yes, treating resources that are _{handwave handwave}_ supposed to be per-request as if they were annotated with `@RequestScoped` from a CDI perspective is probably the right thing to do at some abstract level.

And now a digression on JAX-RS and lifecycles (this is actually relevant! No, really!):

It is worth noting that if (again, pure JAX-RS here, no CDI, no MicroProfile) a user defines an [`Application`](https://jax-rs.github.io/apidocs/2.1/javax/ws/rs/core/Application.html) such that its [`getSingletons()` method](https://jax-rs.github.io/apidocs/2.1/javax/ws/rs/core/Application.html#getSingletons--) returns a resource instance, then it is that resource instance and none other that should be used.  If instead a user defines an `Application` such that its [`getClasses()` method](https://jax-rs.github.io/apidocs/2.1/javax/ws/rs/core/Application.html#getClasses--) returns a resource class, then regardless of whether an instance of that class appears in the return value of `getSingletons()`, the lifecycle should be per-request.  (If a user does not define an `Application` at all, then the behavior is up to the JAX-RS implementation as to what to do.)

These `Application` methods are the only portable ways to define lifecycles in JAX-RS; that is: **JAX-RS has no notion of scope annotations at all.**

Obviously JAX-RS implementations can add capabilities here and both Jersey and RestEasy do.

Jersey augments all of this by also permitting `javax.inject` scope annotations on resource classes.  So if a resource class handled by Jersey has `@Singleton` on it, and if that resource class is among the set of `Class`es returned by `Application#getClasses()`, then although that _normally_ indicates to the `Application`'s caller that a per-request lifecycle is desired&mdash;nevertheless `@Singleton` will trump here in Jersey: only _one_ instance of that resource class will be instantiated, and it will be instantiated by Jersey (not the user or the `Application`), and will be dependency injected by whatever Jersey is using for dependency injection.

Next, Jersey [supplies a CDI integration component](https://github.com/eclipse-ee4j/jersey/tree/master/ext/cdi/jersey-cdi1x), used by Helidon, and it puts CDI on top of its dependency injection facilities.  So now resource classes returned from `Application#getClasses()` are instantiated by CDI if they are known to CDI and in the scopes that they are annotated with.

So when CDI is in the picture, as it is in MicroProfile, and therefore as it is in Helidon MicroProfile, and when you want to use behavior that is non-portable with respect to JAX-RS like auto-detecting lifecycles and/or auto-detecting resource classes and so on, you have to make CDI aware of the classes in question.  (We should also double-check and make sure that `Application#getSingletons()` instances are shoehorned into CDI in either `@ApplicationScoped` or `@Singleton` scope; I assume the Jersey CDI support does this?)

CDI becomes aware of classes when bean discovery happens.  [Bean discovery broadly speaking can take place over all Java classes or only those with bean-defining annotations](http://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#bean_archive).  (That is a vastly oversimplified summary but correct as far as it goes.)  Normally you set the bean discovery mode to `annotated`, which means that only those classes annotated with `@RequestScoped`, `@ApplicationScoped`, `@Dependent`, and so on&mdash;but not, notably, `@Singleton`!&mdash;become known to the CDI container.

So fine: if your resource-class-that-you-want-to-be-known-to-CDI doesn't have one of these annotations on it, then CDI doesn't know about it.  If CDI doesn't know about it, and you're in an environment where Jersey is in play and Jersey's CDI support is in play (such as is the case in Helidon MicroProfile), then the behavior is going to be undefined.  In this case, it looks like Jersey's CDI support will see if CDI knows about the requested injection, which as we've already determined it doesn't, and if CDI says "nope" then it goes and tries to do it itself using HK2.

The easiest way of course to solve this problem is to put an explicit bean-defining annotation on a resource class you're planning on using with Helidon MicroProfile server, such as `@Dependent` or `@RequestScoped`.  That should do the trick with a minimum of fuss.  (It may even be part of the MicroProfile specification somewhere as to how to reconcile its requirement of CDI and the requirement of JAX-RS since strictly speaking by both specifications read separately this combination's behavior is undefined.  Java EE if I remember right is where, and only where, the specification of the behavior that should result from these two specifications' co-presence is defined.)

When for whatever reason that is not an option, the next least-magic way to solve this problem is to programmatically inform the CDI container itself that it should consider the resource class as a bean in a particular scope.  You can do this in a portable extension, which can use the [`BeforeBeanDiscovery#addAnnotatedType(Class, String)`](http://docs.jboss.org/cdi/api/2.0/javax/enterprise/inject/spi/BeforeBeanDiscovery.html#addAnnotatedType-java.lang.Class-java.lang.String-) method.  The returned "configurator" can be used to add the `@RequestScoped` or `@Dependent` annotation directly.  Obviously you want to do this only for resource classes that are not already annotated with bean-defining annotations.

Finally you can change Helidon MicroProfile server to take any resource classes that are added to it programmatically via the `Server.Builder#addResourceClass(Class)` method to also [add such classes into the CDI container](http://docs.jboss.org/cdi/api/2.0/javax/enterprise/inject/se/SeContainerInitializer.html#addBeanClasses-java.lang.Class...-).  Currently this addition does not occur.  This step is basically another formulation of the portable extension strategy spelled out one paragraph above.

**Comment by ljnelson** [comment]
Ken Finnigan has [some input here](https://github.com/eclipse/microprofile/issues/49#issuecomment-425561535) that will serve provisionally in place of an actual specification.

**Comment by tomas-langer** [comment]
It seems the agreement is that `@Dependent` scope is closest to what is defined by both JAX-RS and CDI specs.
When in Dependent scope, a new instance would be created each time it is requested from CDI, so the lifecycle of the JAX-RS resource is left fully to JAX-RS

**Comment by spericas** [comment]
This is a tricky one ... There are many other injectable things in JAX-RS (via `@Context` mostly) which are also _per-request_ that, if injected in different locations (like in 2 different filters during the same request processing), developers would expect the same instance. With CDI, you could even inject an instance of a resource class also, although that's not common at all.

If we move to `@Dependent` then each of those injection points will be fulfilled by a different instance. You could make the argument that all JAX-RS artifacts should be handled in the same CDI scope, not in a mix of them. 

The other use case the needs more exploration (unless someone has done it already) is async calls. These normally respond on a separate thread, and I wonder if there are any consequences if we move to `@Dependent`. As Laird stated, others have preferred the use of `@RequestScope` before.

**Comment by tomas-langer** [comment]
The `Dependent` scope is only for CDI - it is Jersey's responsibility to inject stuff correctly.
Injection using `@Context` is not handled by CDI but by HK2 (AFAIK), so this should not be an issue
I have not tried making a filter a CDI bean... Nevertheless you would not inject a resource class into a filter anyway, so there should not be an issue, right?

**Comment by spericas** [comment]
The moment CDI is enabled in a JAX-RS application, everything it provides (resources, filters, interceptors, etc) can become a CDI bean. At least on paper, anything could be injected into anything else, and there's no way to prevent that. Is this a common use case? It is not.

The JAX-RS spec states that certain things are instantiated _per request_. If a constructor for one of those beans is called more than once during the processing of a request (because `@Dependent` is assumed by default), it would be a violation. 

Future JAX-RS versions will drop support for `@Context` and I would imagine `@RequestScope` would be preferred over `@Dependent` for resources, but we shall see. 

There's also the issue of async calls (that can span threads) that may be a problem if resource instances are not linked to threads in any way --but this is more of an implementation problem, I think, and perhaps a topic to discuss with the Jersey guys.

**Comment by tomas-langer** [comment]
This is now merged.
Helidon now adds all resources annotated with `@Path` as beans.
Default scope is `@Dependent`, user can define any scope desired.
