### ISSUE TITLE
Documentation: table formatting in Security Providers page is difficult to read

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#1599]
## Environment Details
* Helidon Version: 1.4.4

----------

## Problem Description
As reported by the user:

"This page is really difficult to read. It it possible to remove the table__overflow  class to 
allow the contents to wrap? (Slight alternating row colours would be a bonus too!) :slightly_smiling_face: https://helidon.io/docs/latest/#/security/02_providers"

**Comment by ljamen** [comment]
@barchetta @m0mus,
I realize this a a low priority issue, but I'm running into this in other topics as well. Is there a global change that can be made and applied to all existing tables ( table overflow class)? I'm hesitant to use tables at all right now because of the way some are rendering. Sometimes bulleted lists aren't a great substitute.

**Comment by m0mus** [comment]
@danielkec can you take a look on this issue?

**Comment by danielkec** [comment]
@ljamen We can do some fine tuning of the default mode, can it be like this? oracle/helidon-build-tools/pull/104

**Comment by ljamen** [comment]
The wrapped table is better. Ideally we could limit the spread of the table to 75% so that it wrapped even more, but in this case a table probably shouldn't have been used. Will these changes automatically apply to the existing tables in the site or do we have to go in to each topic and adjust?

**Comment by danielkec** [comment]
PR oracle/helidon-build-tools/pull/104 is part of 2.0.0-M3, can we close this issue?

**Comment by barchetta** [comment]
Yes. That looks good enough for me!
