### ISSUE TITLE
OutputStreamPublisher should buffer data

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#1833]
When we send single bytes to output stream publisher, the performance is very bad.
We should buffer bytes when not requested by subscriber into one or more byte buffers.
Only when the buffer(s) are full, we should force waiting on subscriber.

Currently we send each byte[] received to subscriber and wait 250 ms if not requested.

When we receive 1000000 single bytes, this breaks and times out. If buffered, this works fine.

**Comment by tomas-langer** [comment]
Create:
- unit test that makes sure this works fine for bigger arrays
- unit test that makes sure this works fine for single item arrays

**Comment by spericas** [comment]
This code has changed significantly in 2.0. I suspect the issue may still be present whenever we call `MultiFromOutputStream::write(int)` since this results in a single-byte array created and published. Does anyone have an actual example showing the problem? A JAX-RS resource that uses `StreamingOutput` may exhibit the problem perhaps.

**Comment by spericas** [comment]
@tomas-langer @jansupol Spent some time analyzing this buffering issue in `MultiFromOutputStream`. As I understand it, the original problem was found by Jan in the context of the Jersey/Helidon connector. 

Based on my tests, the other strategies implemented by the Jersey/Helidon connector for sending data appear to run much faster than anything using `MultiFromOutputStream` _even after_ experimenting with various buffering optimizations. 

The main problem in `MultiFromOutputStream` is that every call to `write` results in an array being published. This is fine when writing normal arrays (like in a typical JSON response) but slow if writing single bytes at a time (like `StreamingOutput`) as each one is converted into a single-byte array. Some possible improvements:

1. Combine all writes of single bytes and arrays into larger buffers and reduce the number of buffers published. This will help the connector but sort of breaks the `Multi` abstraction and certainly breaks multiple tests that expect one published event per write.

2. Combine only the single-byte writes into an array. This options does not break any of our existing tests, may help certain applications but does not help the connector at all. This is because the connector happens to write as follows: byte, array, byte, array, etc. 

At this time, our best bet is to continue to use the byte channel approach in the connector (instead of `Multi`) and to, optionally, implement (2) as it may help certain apps. I actually have an implementation of (2) with tests ready.

**Comment by tomas-langer** [comment]
I would implement 2 as I think nobody expects that writes to an output stream would result in single byte publisher. I agree that this should only work for single bytes (has to have a decent handling of "single", "single", "array" - probably two arrays sent by publisher). Usually when you write buffers to `OutputStream` you "declare" you want that buffer to be the published array.

So I agree with your recommendation.
