### ISSUE TITLE
[OpenAPI] Downloading an empty document

### ISSUE THREAD

**Issue by cajasmota** [oracle/helidon#2108]
## Environment Details
* Helidon Version: 1.4.1 - 1.4.5 - 2.0.0
* Helidon MP
* JDK version: Zulu 8, Zulu 11, GraalVM 11, OpenJDK 11
* OS: Windows 8,  macOS Mojave and an experimental Alpine Linux on Android via Termux
----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"
While doing an [experiment](https://twitter.com/cajasmota/status/1277414649290514432) of running several servers / frameworks on my Android phone using Termux, Alpine Linux and OpenJDK  11 I found that on version 2.0.0 the falult tolerance API and Open API was not working at all.

I Assumed that was not important because it was a very experimental environment, but running the same jar compiled witn `mvn clean package` using the code generated by [MicroProfile Starter](start.microprofile.com) on my Windows Machine and my Macbook pro I found the same issue with OpenAPI. 

I recompiled the jar changing the helidon version on pom xml using 1.4.1, 1.4.5, 2.0.0

You can download that jar from [here](https://jcajas.dev/experiments/helidon.zip) (helidon 1.4.5)
That jar was compiled using ` GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07)` on Windows 8.1

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
[//]: # "Provide sample code/application if relevant"

On any OS / JDK configuration when I navigate to the /openapi ednpoint, the browser downloads a file without extension, and if you try to open that file with a text editor is an empty OpenAPI file with this content.

```
---
openapi: 3.0.1
info:
  title: Generated API
  version: "1.0"
paths: {}
```

**Comment by tjquinno** [comment]
The structure and inheritance of the Helidon poms has changed since 1.4.1, and the MP starter currently uses 1.4.1 in its generated code. 

Simply changing the Helidon version in the starter-generated pom is, therefore, insufficient to build a 1.4.5 or 2.0.0 project correctly.

We will be in touch with the Starter folks and get this corrected.

In the meantime, using the Helidon CLI or the Helidon QuickStart will work:

MP QuickStart 
For 1.4.5: https://helidon.io/docs/1.4.5/#/guides/03_quickstart-mp
For 2.0.0: https://helidon.io/docs/latest/#/mp/guides/02_quickstart

CLI for 2.0.0:
Linux: http://helidon.io/cli/latest/linux/helidon
Mac: http://helidon.io/cli/latest/darwin/helidon

**Comment by tjquinno** [comment]
We've just completed updates to the MP starter so choosing Helidon and a given MP release uses the latest corresponding Helidon release. See https://github.com/eclipse/microprofile-starter/pull/352
