### ISSUE TITLE
Default configuration files

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#2171]
Currently the default configuration files are hardcoded (`application.yaml`, `application.properties`)

These should be defined by appropriate `ConfigParser` or `ConfigSource` implementation, so we only look for the sources currently supported (and also we may add new default configuration files without changing Helidon config code).

**Comment by bruno-oliveira** [comment]
Hello,
Could I work on this issue? :)

**Comment by bruno-oliveira** [comment]
Should I create additional implementations for the `ConfigParser` and `ConfigSource` interfaces, or can I for instance adapt an existing implementation of for example `ParsableSource`? Like setting some default values in `FileConfigSource`? 

I assume we do not want to replace references everywhere in the codebase to `application.properties` with new references via a `Source`, right? This is just so we can load them directly when we want to from a unit test for example, right?

<img width="780" alt="Screenshot 2020-07-22 at 00 18 10" src="https://user-images.githubusercontent.com/4722412/88116626-e5e69d00-cbb0-11ea-87c5-17afe31354e7.png">

So, we do not want to touch the JSON, but in the tests, after this work would be done, we could do something like:

```java
DefaultConfigParserBuilder builder = new DefaultConfigParserBuilder("/my-new-file.newformat");
DefaultConfigParser parser = builder.build();
Config cfg = parser.parse();
```

And then instead of referencing paths with a particular `application.properties` or yml, we just use the `cfg` object?

**Comment by tomas-langer** [comment]
Hello Bruno. Sorry for the late reply. The intention here is to update the SPI of ConfigSource and/or ConifgParser to add a method that would provide a list of file names that should be discovered. 
This way we could look for default files automatically, without hardcoding them.


The expected API would be:
`Config config = Config.create()`

And if you have `yaml` parser on classpath, `application.yaml` and maybe `application.yml` would be automatically added as default config source.

The config itself would not be aware of any default configuration sources, it would always read them from parsers and sources

**Comment by tomas-langer** [comment]
As this is quite an important API/SPI in Helidon, I would prefer to do this part within our team. If you are still interested in contributing to Helidon, please contact me and I can find a good issue to start with Helidon! 
Easiest way to contact us is through our Slack channel: https://helidon.slack.com
