### ISSUE TITLE
Doc: SE Metrics 2.0 - add new use cases

### ISSUE THREAD

**Issue by ljamen** [oracle/helidon#2196]
## Environment Details
* Helidon Version: 2.0.3
* Helidon SE 

----------

## Problem Description
Remaining doc tasks from Doc Epic 1515 https://github.com/oracle/helidon/issues/1515
Update the SE Metrics doc with additional use cases and any notable changes for 2.0. 

## Steps to reproduce
Review existing doc here: 
https://helidon.io/docs/v2/#/se/metrics/01_metrics

**Comment by tjquinno** [comment]
There are no changes required due to the update to metrics 2.0.

The existing SE page shows an example of adding a metric to a service and then defers to MP metrics for working with other types of metrics. This seems like the right amount of detail to me. Not sure what adding any more use cases would add to a reader's understanding, so I'll close this without requiring any changes to the doc page.
