### ISSUE TITLE
Package private methods broken in some CDI proxies

### ISSUE THREAD

**Issue by martin-sladecek** [oracle/helidon#2223]
## Environment Details
* Helidon Version: 2.0.1
* Helidon MP
* JDK version: 11.0.8
* OS: Linux
* Docker version (if applicable):

----------

## Problem Description
When a proxied object is created through a producer (in a different package than the object class, which might be from a library), it's package-private methods will be broken, returning default field values instead of actual bean values.

## Steps to reproduce
See attached example. SampleProcessor internal logic is broken because of invalid proxy.
[example.zip](https://github.com/oracle/helidon/files/5002788/example.zip)

**Comment by ljnelson** [comment]
This is not a Helidon bug.

The root issue, I think, is that `Sample` is an unproxyable bean type according to https://jakarta.ee/specifications/cdi/3.0/cdi-spec-3.0.0-M4.html#unproxyable.  Specifically, it does not have a no-argument constructor.  Note that unproxyability seems to apply to bean _types_, not just managed beans, so it applies even in the case where you're producing something with a producer method.

Now, what is odd is that I _think_ Weld is supposed to treat this as a deployment problem and is supposed to prevent your application from running at all.  Nevertheless, your application runs.

I'm continuing to debug this as I'm not entirely happy with this state of affairs yet.  Specifically, I can't see (yet) how Weld is actually proxying the `Sample` instance that is produced by your producer method.  I can see your producer method is called, but then Weld is clearly creating a proxy instance of `Sample`, whose internals are properly forwarding method calls to a "real" instance of `Sample`, but that "real" instance has been created seemingly not by your producer method.  It appears to have been created, mysteriously, by the invocation of a non-existent zero-argument constructor or some other trickery such that its `name` field is set to `null`.

**Comment by ljnelson** [comment]
Aha.  Weld is indeed trying to inform you that your producer method is invalid, but for some reason the exception is eaten or swallowed. 
![Screen Shot 2020-07-31 at 1 08 50 PM](https://user-images.githubusercontent.com/80764/89073324-17890200-d32f-11ea-8c6a-25d369032661.png)
So there _is_ an issue in either (a) Weld (doubtful), (b) Jersey, (c) the Jersey-supplied-HK2-to-CDI-binding library or (d) Helidon's logging of the intersection of all these technologies.  Then despite the fact that this deployment should have failed, somehow Helidon's usage of Weld allows the application to continue running.  I'm guessing that at the point that injection of your `Sample` class occurs, it is actually injected by HK2.

Somewhat bizarrely no combination of breakpoints that I can use (including one set in an instance initializer!) allow me to see a `Sample` instance created by anybody.  The first breakpoint I see is when its `getName()` is called.

Now I'm intrigued.  This state of affairs is extremely weird.  Again, the long and short of it is: you have a bad producer method.  That should have stopped the application from even starting.

**Comment by ljnelson** [comment]
I stand corrected; your `Sample` type is indeed proxiable.  Still digging.

**Comment by ljnelson** [comment]
This is one of the strangest things I've ever seen in all my years of working with CDI.  I cannot set a breakpoint anywhere in `Sample` that shows it ever being instantiated.  Yet the breakpoint that I set in its `getName()` method is hit and `null` is returned, suggesting that something has instantiated this class without (a) using your constructor, so most notably although your producer method is found and registered it is never invoked, and (b) triggering an instance-level initializer I put in to see if I could trap instantiation.  The short answer is I have no idea how a `Sample` object is coming into existence.  It is definitely the case that whatever is instantiating it is using something like `Unsafe` to do so in some way that bypasses the JLS-defined instance-level initializer, which I didn't even know was possible, and which allows the `final` `name` field to be unset (which I also didn't know was possible).

By the point that all this craziness happens Helidon itself is out of the picture, so it should be possible to put together a CDI 2.0 standalone project that demonstrates this issue.

(I'm still not comfortable with the fact that Weld concludes that `Sample` is proxiable.  I still think it is a bean type that should be unproxyable by spec, but Weld concludes that it is fine.  I expect something in here is going to prove to be the culprit.)

**Comment by ljnelson** [comment]
More notes mostly to self.

Indeed somewhere in all of this `Unsafe#allocateInstance()` is being called on `Sample`, such that all constructors are bypassed.  That is not surprising, as Weld needs to proxy the instance of `Sample` that your producer method is making.  So this actual-instance-of-the-proxy-class is built using `Unsafe#allocateInstance()`.  That should be fine.

Then I can see that this proxy instance is being injected into the field injection point in your resource class.  Great.  So then operations from within your resource class on its `sample` field should be just fine: they should go "through" that `Sample` proxy "into" its "real" `Sample` instance made by your producer method.  Except in this case the package-level `getName()` method does exactly what you say, i.e. it looks up the value of the `final name` field _on the proxy itself_, which of course is `null`, because the proxy itself was instantiated using `Unsafe`.

The question is: if Weld is going to all the trouble to _subclass_ `Sample` for the _express_ purpose of being able to "see" package-private methods such as `getName()`, then why would the `Sample` proxy not employ its `ProxyMethodHandler` on the invocation of `getName()` upon the proxy?  That certainly appears to be what is happening.

Finally for completeness this sort of thing is definitely in the gray area of the specification, but I am pretty sure Weld intends to handle situations like this.

**Comment by ljnelson** [comment]
Hmm; I can see that Weld is encountering the `getName()` method during proxy construction, and is indeed trying to generate a forwarding method body for it.  Then it gets here:

https://github.com/weld/core/blob/369c0c7e1c42f3522b3fee41d67e4caee7bd8446/impl/src/main/java/org/jboss/weld/bean/proxy/ClientProxyFactory.java#L174-L187

`bytecodeInvocationAllowed` is set to `false` here.

**Comment by martin-sladecek** [comment]
Hi Laird, the constructor should have been annotated by @Inject annotation, sorry for misleading you. I think the problem is somewhere around HelidonProxyServices. They try to create the proxy in the same package as the originalClass, which is the producer bean in this case.

**Comment by ljnelson** [comment]
No, the constructor for `Sample` does not need to be annotated, because all contextual instances of `Sample` should be produced by your producer method.  I'll look at `HelidonProxyServices` later but my assessment above is a result of watching the actual objects get built and walking the bytecode.

**Comment by ljnelson** [comment]
One other question: this sounds like maybe you are experiencing this as part of our CDI-in-native-image feature.  Do you experience this problem when simply running using Java (I experienced the issues I noted above)?

**Comment by ljnelson** [comment]
Aahhhh, wait, now I'm getting it.  Investigating.

**Comment by tomas-langer** [comment]
The problem we get with Helidon 2:
```
    public static String doSomethingWithSample(Sample sample) {
        Class<?> sampleClass = Sample.class;
        Class<?> proxyClass = sample.getClass();

        Package samplePackage = sampleClass.getPackage();
        Package proxyPackage = proxyClass.getPackage();
```
`samplePackage` and `proxyPackage` both have the same value (`io.helidon.examples.quickstart.mp.other`), but are NOT equal.
This is caused by a difference in module loading them - both are in `unnamed module`, but with different hash codes (even when running on classpath).

Need to investigate why this would happen.

**Comment by tomas-langer** [comment]
Found the problem in `HelidonProxyServices` - this is design to make Helidon CDI work with module system. I will try to modify this to work with this use case.

**Comment by tomas-langer** [comment]
I have modified the services to attempt to use private lookup and only use a different classloader if private lookup fails - this fixes this problem.
