### ISSUE TITLE
io.helidon.faulttolerance.RetryTest.testTimeout fails intermittenly

### ISSUE THREAD

**Issue by romain-grecourt** [oracle/helidon#2258]
```
java.lang.AssertionError: 
Should have been called twice
Expected: is <2>
     but: was <1>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at io.helidon.faulttolerance.RetryTest.testTimeout(RetryTest.java:138)
```

**Comment by tomas-langer** [comment]
This will be a tricky one.
I have tried repeating this 100000 times on my computer and it fails to replicate (as it is always fast). This is most likely caused by overall slow CPU that allows this test to retry only once (even though it should do it twice).
As with other timeout based tests we have two options:
1. increase the times to allow for slow execution (increases overall testing time of Helidon)
2. disable the test and only run it locally on change

**Comment by dansiviter** [comment]
I find [awaitility](https://github.com/awaitility/awaitility) useful in these scenarios. This should mitigate the impact in an increase in times on fast hardware and only be a problem for those that need it.

**Comment by spericas** [comment]
PR #2287
