### ISSUE TITLE
Add Support of OCI Vault into Helidon

### ISSUE THREAD

**Issue by paulparkinson** [oracle/helidon#2416]
This is the same topic as https://github.com/oracle/helidon/issues/2395 "Add Support of Hashicorp Vault into Helidon" but specifically the OCI Vault service and, like that ER, we are researching best approaches to this particularly as there are a number of solutions and approaches in this area.

**Comment by tomas-langer** [comment]
It would be good to understand what features are desired for OCI vaults (ideally with a reference to an SDK function, or REST API).
After playing around with the SDK, it seems there is no way to retrieve the actual secret value from a Vault, which seems to be the real use case I can see here.

I do not think that creating/updating secrets is the usual use case (please let me know if this assumption is wrong).

**Comment by tomas-langer** [comment]
Found the  `getSecretBundle()` method that can actually return secret content, looking into it.

**Comment by tomas-langer** [comment]
Notes for follow up (I will create issues for these)

- Add CDI module with blocking/synchronous methods equivalent to the current reactive ones (e.g. return the Response directly rather than return a `Single<Response>`
- Maybe add explicit support for tracing (can be enabled now through builder, by adding the tracing client service, or through configuration by enabling services + configuration)
- DTTO for metrics in SE/MP

**Comment by trentjeff** [comment]
Discussed with @tomas-langer , we can close this issue.
