### ISSUE TITLE
Remove dependency on jakarta activation from examples and project templates

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#2578]
The following dependency is in all generated projects and in our examples:
```
        <dependency>
            <groupId>jakarta.activation</groupId>
            <artifactId>jakarta.activation-api</artifactId>
            <scope>runtime</scope>
        </dependency>
```

This is part of transitive dependencies of weld (and should be provided by `helidon-microprofile` bundle if it was not)

**Comment by bfedoronchuk** [comment]
What is the original purpose of this dependency? Seems like Heldion apps work fine without it (using Helidon MP 2.3.0).

**Comment by barchetta** [comment]
Stripping it down the quickstart to the core MP server and activation gets brought in transitively via ` jakarta.xml.bind:jakarta.xml.bind-api`

```
[INFO] |  |  +- io.helidon.webserver:helidon-webserver-jersey:jar:2.3.1:compile
[INFO] |  |  |  +- io.helidon.jersey:helidon-jersey-server:jar:2.3.1:compile
[INFO] |  |  |  |  +- org.glassfish.jersey.core:jersey-server:jar:2.34:compile
[INFO] |  |  |  |  |  \- jakarta.validation:jakarta.validation-api:jar:2.0.2:compile
[INFO] |  |  |  |  \- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.3:compile
[INFO] |  |  |  |     \- jakarta.activation:jakarta.activation-api:jar:1.2.2:compile
```

So why is this in the examples? I think this is left over from 1.x where something, either CDI or Jersey I think, was complaining. And we had to add the direct dependency to silence it. And it's been carried along ever since.

Bottom line: we should be able to remove this, but I wish I could remember why it is there. Might  do a little more digging.

**Comment by barchetta** [comment]
Went back all the way to 0.10.0. It was Jersey:
```
WARNING: HK2 service reification failed for [org.glassfish.jersey.message.internal.DataSourceProvider] with an exception:
MultiException stack 1 of 2
java.lang.NoClassDefFoundError: javax/activation/DataSource
```

**Comment by ljnelson** [comment]
Just for posterity [we should be aware of what we're not supplying](https://jakarta.ee/specifications/restful-ws/3.0/jakarta-restful-ws-spec-3.0.html#standard_entity_providers); for the record I think this is fine but now there's a link.
