### ISSUE TITLE
Config examples: cleanup

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#273]
Some issues with the config examples:

- [x] `changes` example uses a deprecated API
- [x]  `git` example uses repo `https://github.com/okosatka/`. We should probably use a repo under https://github.com/helidonrobot/ 
- [x] Flesh out readmes

**Comment by tjquinno** [comment]
About the use of `@Deprecated` methods on `Config`...

1. The `ChangesSubscriberExample` example code refers to `Config.changes` which is marked as deprecated because it exposes a "temporary" Helidon API that mirrors one from the JDK 9 and later Flow support. We decided to mark it as deprecated to discourage developers from relying too heavily on it and therefore propagating the use of the temporary API throughout their own code. I propose
