### ISSUE TITLE
Batch support

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#2785]
Investigate if batch support would be a good feature for Helidon.

See Jakarta batch: https://jakarta.ee/specifications/batch/2.0/apidocs/

**Comment by dalexandrov** [comment]
JSR 352 or JBatch is mainly designed to work in a managed EE environment. It requires JPA, JTA naming services etc. to work properly. Helidon is not a full EE container, thus JBatch cannot work correctly.
For making it work in Helidon we can use one of the “so called” standalone (SE) implementations of JBatch.
For Helidon 2.x  IBM JBatch 1.x version can be used, since it is in “javax” namespace;
For Helidon 3.x IBM JBatch 2.x version can be used, since it is migrated to “jakarta” namespace;

There is limitation with name resolution in “Stand Alone” mode, thus all bean names should be specified as fully qualified strings. 
The current joint technology usage I find enough.
 
Currently there is an article about this joint technology usage: https://medium.com/helidon/helidon-and-jbatch-2826eec478a2
This article can be reworked as an official guide.

IBM JBatch version can be upgraded to 2.x after Helidon 3.x is released, since they both will be in “jakarta” namespace.

**Comment by dalexandrov** [comment]
The current decision is to focus on joint technology usage. 
For Helidon 3.x the article should be updated to use "jakartified' version of IBM JBatch.

**Comment by ljamen** [comment]
See #3895 for doc.
