### ISSUE TITLE
@PostConstruct in RestApplication invoked twice when using openapi

### ISSUE THREAD

**Issue by bogedal** [oracle/helidon#2799]
## Environment Details
* Helidon Version: 2.2 (2.2.1 has the issue to)
* Helidon MP
* JDK version: 11
* OS: Windows
----------

## Problem Description
Seem that using the implementation (implementation 'io.helidon.microprofile.openapi:helidon-microprofile-openapi') triggers Helidon to invoke the @PostConstruct in the RestApplication class twice.

## Steps to reproduce
I've included a sample project for reproduction of the issue.
Running the sample project will print "-----> PostConstruct has been invoked <-----" in the console everytime it invokes the @PostConstruct function

[sample-project.zip](https://github.com/oracle/helidon/files/6043361/sample-project.zip)

**Comment by tjquinno** [comment]
I posted an earlier comment and removed the "bug" designation perhaps a bit too quickly. I am still looking into this.

**Comment by tjquinno** [comment]
(I found a separate odd bit of behavior but it is not causing the double-invocation of the post-construct method.)

This is as-designed. (Whether we should change the design is a separate and interesting question, and we're actually talking about that, but this is how it's intended to work currently.)

Normally, Helidon MP OpenAPI gets all the information it needs about your JAX-RS application and resource classes from the Jandex index we recommend you build into your app. But Helidon does not require the index. 

If Helidon MP OpenAPI finds no Jandex index during start-up, it logs a warning to that effect and then does its best to create an in-memory index dynamically. To avoid scanning every class that's accessible, Helidon looks for each `Application` class (typically there is one) and invokes its `getClasses` and `getSingletons` methods. In order to invoke them Helidon needs to create an instance of the app class because those are instance methods.

So Helidon:

1. Uses CDI to create an _unmanaged_ instance of each `Application` class.
2. Instructs CDI to perform any injection _and post-construct_ logic specified on the class, in case those actions might affect the results returned by `getClasses` and `getSingletons`.
3. Invokes those two methods, storing the classes represented by the returned values.
4. Disposes of the unmanaged instance. 

This triggers the first invocation of any post-construct method.

Later, JAX-RS searches for a pre-existing instance of the `Application` class and, finding none (because the earlier processing created an unmanaged instance and disposed of it), instantiates the class again, this time as a _managed_ instance.

That triggers the second post-construct invocation. Note that the two invocations are on  _different_ instances of the `Application` class.

Now, ideally the post-construct method performs any further initialization required of the object being created, without inducing any side-effects elsewhere. That said, this is clearly not a requirement and side-effects are possible. If the post-construct logic that induces side effects is not idempotent, then Helidon invoking the post-construct methods twice could be an issue.

You can avoid this situation entirely if you create and package a Jandex index with your application JAR. Our examples (which are Maven-based) show how to use a Maven plug-in to do this. I know your sample project uses Gradle, and a quick search for Gradle plug-ins for Jandex turned up three. There might be more, and I have never used any of the three I found so I cannot offer any advice for or against any of them.

**Comment by bogedal** [comment]
Thanks a lot for the very quick reply.
I know that I use Jandex in my main project, but removed it to keep this sample-project .. well ... simple :)
I'll try and incorperate Jandex and see if the issue persists

**Comment by bogedal** [comment]
I've created a sample-project which utilizes Jandex and I have verified that the jandex.idx file is present in the .jar file,
However the @PostConstruct is still being invoked twice.
I've attached the updated sample-project
[sample-project-with-jandex.zip](https://github.com/oracle/helidon/files/6047919/sample-project-with-jandex.zip)

**Comment by tjquinno** [comment]
Oh, yes. You're absolutely right. The code _does_ always create the unmanaged instance of each `Application` and invoke `getClasses` and `getSingletons`, whether the Jandex index is present or not. 

Upon further review and reflection, I believe this is the purpose behind the behavior: If there are multiple `Application` instances, the internal OpenAPI model for each should reflect only the classes required by that instance. For example, suppose there were both a `CustomerApp` with endpoints that referred to an `Address` class and an `InventoryApp` with endpoints that referred to a `Part` class. We would not want the OpenAPI model for `CustomerApp` to contain `Part`, or the model for `InventoryApp` to contain `Address`.

To accomplish this, the code instantiates each `Application` class so as to invoke its `getClasses` and `getSingletons` methods to find out what other classes need to be part of that app's internal OpenAPI model.

We might be able to change how this works, but it would take some non-trivial effort. It costs some performance but for a good goal, one could argue. 

The question then becomes whether this double-instantiation is creating _bugs_ in your app. Remember that the post-construct method is invoked only once on any given instance of the class.

**Comment by bogedal** [comment]
Im my service this double instantiation prevents the server from staring up due to some prometheus metrics registration.
These are global and unique, so an exception is thrown upon the second instantiation.

This can be handle differently but this is my current issue.

**Comment by tjquinno** [comment]
Understood. I will look into what practical ways there might be to change the Helidon code to avoid the double-instantiation. It probably won't be something that's available really quickly, though, so to avoid this blocking you maybe you can consider doing something like this in your application class:

```
public class MyApp extends Application {
    private static AtomicBoolean isPrometheusCollectorCreated = new AtomicBoolean();

    @PostConstruct
    public void postConstruct() {
        if (!isPrometheusCollectorCreated.getAndSet(true)) {
            PrometheusStatsCollector.createAndRegister();
        }
    }
}
```

**Comment by bogedal** [comment]
Thanks - Much appreciated @tjquinno
