### ISSUE TITLE
WebClient should auto-populate content-length header if not explicitly set

### ISSUE THREAD

**Issue by Two4** [oracle/helidon#2808]
As seen in the following code, I have to explicitly set the content-length header when sending requests with WebClient, or else I get `411 Content-Length Required` responses. Luckily this particular request doesn't have a body, but if it did, it would be difficult to determine the actual payload length using this builder-style pattern to construct requests.
````
    private static void getToken(String code) {
        logger.info("Getting new Google Drive access token");
        JacksonSupportShim.registerDeserializer(OAuthToken.class);
        WebClientRequestBuilder requestBuilder = webClient.post()
                .uri(GoogleCredential.getTokenUri())
                .contentType(MediaType.APPLICATION_FORM_URLENCODED)
                .queryParam("client_id", GoogleCredential.getClientId())
                .queryParam("client_secret", GoogleCredential.getClientSecret())
                .queryParam("code", code)
                .queryParam("grant_type", "authorization_code")
                .queryParam("redirect_uri", GoogleOAuthService.getRedirectUri());
        requestBuilder
                .headers().contentLength(0L);
        requestBuilder
                .readerContext().registerReader(JacksonSupportShim.get().readerInstance());
        try {
            token = requestBuilder.request(OAuthToken.class).get();
            logger.info("Google Drive access token retrieved");
        } catch (InterruptedException | ExecutionException e) {
            fatal(logger, e);
        }
    }

**Comment by tomas-langer** [comment]
`Content-Lenght` should be set by webclient only in the following cases:

- there is no entity and the HTTP method may have an entity - set to `0`
- there is a small entity, that fits into one "chunk" (our representation of byte buffer) - set to the length of that buffer 
- otherwise we always use chunked encoding, which (by HTTP specification) does not use a content length (as it may not be known)

The last case is quite important - when we send bytes using publishers, we do not know the entity size in advance, and we will not buffer it (as this is a dangerous operation - what if the entity is 1 GB big?). So we use chunked encoding to send the entity as it comes. In these cases the content length cannot be computed - and it should either be provided by the user (such as when sending a file - you can get the file length, configure `Content-Length` and then send it).

There is an issue right now that `Content-Length` is removed when using chunked encoding, which should not happen (it may still be ignored by the server, but we should send it if configured).

**Comment by tomas-langer** [comment]
The `411 Content-Length Required` - that is also a question of the remote server and application implemented on it. The specification requires `Content-Length` when not using chunked encoding only (which we actually use in most cases).
