### ISSUE TITLE
Jaeger-client-0.35.5 and libthrift-0.12.0 Security Issue 

### ISSUE THREAD

**Issue by KrishnaUpadhyay36** [oracle/helidon#3278]
## Environment Details
* Helidon Version: 1.4.8
* Helidon MP
* JDK version: 1.8
* OS:
* Docker version (if applicable):

----------

## Problem Description
Hi Team, 

In the recent OWASP report for helidon-1.4.8, we see that libthrift and Jaeger-client dependency of helidon tracing has a high and medium security issue respectively. We confirmed the same by checking it in the following URL
https://nvd.nist.gov/vuln/detail/CVE-2019-0210.
helidon-1.4.9 is also using libthrift-0.12.0. We have verified libthrift-0.14.1 and jaeger-client-1.6.0, they are not vulnerable. We are planning to upgrade the helidon version to 1.4.10 but we verified even in 1.4.10 this is vulnerable. 

Can you please let us know if there is a plan for fixing the same

Thanks, 
Krishna Upadhyay

**Comment by barchetta** [comment]
Short answer: these CVEs do not apply to Helidon's and Jaeger Client's use of libthrift.  And these dependencies have been upgraded in Helidon 2.0.

Longer answer: due to incompatible changes in libthrift, Jaeger client and OpenTracing we can't upgrade these dependencies without breaking compatibility with OpenTracing. That's why we did this only in 2.x. It also turns out that the CVEs against libthrift are out of scope of Jaeger Client's use of libthrift because they are against the server component of libthrift, and `jaeger-client` only uses client components of libthrift. More details in the comments here: https://github.com/oracle/helidon/blob/1c36ce7b6f19282361f30643ce7b973545cbdd67/etc/dependency-check-suppression.xml#L139
