### ISSUE TITLE
io.helidon.demo.todos.backend.BackendTests hangs with Java 17

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#3604]
## Environment Details
* Helidon Version: 2.4.0
* JDK version: java 17.0.1 2021-10-19 LTS
* OS: MacOS

----------

## Problem Description
When building `examples/todo-app` the `BackendTests` hangs when building with Java 17. It does not hang with Java 11.

## Steps to reproduce

```
cd examples/todo-app
mvn clean install
```

Command will hang at `[INFO] Running io.helidon.demo.todos.backend.BackendTests`

**Comment by dalexandrov** [comment]
I confirm, that this test hangs with Java 17 on MacOS.

The issue comes from inability of the `EmbeddedCassandraServerHelper` to start. Update Cassandra driver to version 3.1.1 did not help.

The problem comes from:
`org.apache.cassandra.db.commitlog.AbstractCommitLogSegmentManager:86`

AFAIK there is no support of Java 17 in Cassandra Unit.

**Comment by dalexandrov** [comment]
I confirm this issue with JDK 17.

The issue comes from inability `EmbeddedCassandraServerHelper` to start correctly.

`org.apache.cassandra.utils.JVMStabilityInspector` is unable to handle reflection correctly:
`java.lang.reflect.InaccessibleObjectException: Unable to make field private int java.io.FileDescriptor.fd accessible: module java.base does not "opens java.io" to unnamed module @1936f0f5` which as expected for JDK17 causes the app to hang.

Cassandra 3.x, one we are using, supports only Java 8. Cassandra 4.0 has experimental support for Java 11. 
Java 17 support comes with future releases of Cassandra 4+.

More info: https://community.datastax.com/questions/12347/issue-in-launching-cassandra-illegalaccesserror.html

As a temporary solution, we may ignore the test for now, and declare the example has predictable work only with Java 11. As the support is announced, we should upgrade to Cassandra 4+.

**Comment by dalexandrov** [comment]
Test marked as `Disabled`
