### ISSUE TITLE
OCI SDK 2.x is incompatible with Helidon 3

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#3992]
This is a tracking issue.

Helidon 3 supports MicroProfile 5 and Jakarta 9+.  In those versions the Java package names for Jakarta components changed from `javax` to `jakarta` introducing an incompatibility. 

Helidon 3 uses JAX-RS 3.0.0 (jakarta package names) and the corresponding Jersey implementation.  OCI SDK 2.19.1 uses JAX-RS Client 2.1.6 (javax package names) and the corresponding Jersey implementation. Therefore the OCI SDK is incompatible with Helidon 3 applications and any application that uses JAX-RS 3.

The issue has been reported to the OCI SDK team. See  https://github.com/oracle/oci-java-sdk/issues/371

Helidon 2 uses JAX-RS Client 2.1.6 so no issues there.

**Comment by mricken** [comment]
In https://github.com/oracle/oci-java-sdk/issues/371 , I have a little example that successfully uses the OCI Java SDK (with shaded Jakarta 2) and then uses Jakarta 3.0.0 and Jersey 3.0.4 to make an HTTP request.

@barchetta , please take a look if that could be a viable work-around.

**Comment by ljnelson** [comment]
Mostly taking notes here:

(For clarity and posterity: there is no such thing as Jakarta 2 or Jakarta 3.0.0.  I believe the intent of the prior comment is to show the interoperability of the all-inclusive OCI shaded jar file, which shades/aliases its dependencies on, among other things, [Jakarta RESTful Web Services version 2.1](https://jakarta.ee/specifications/restful-ws/2.1/apidocs/), and Helidon's support on the `master` branch for [Jakarta RESTful Web Services version 3.0](https://jakarta.ee/specifications/restful-ws/3.0/apidocs/).)

My understanding is that [in Helidon's code that integrates with the OCI Java SDK](https://github.com/oracle/helidon/blob/2.5.0/integrations/oci/sdk/cdi/src/main/java/io/helidon/integrations/oci/sdk/cdi/OciExtension.java) where we would previously use, say, `javax.ws.rs.client.ClientBuilder` (just an example typed off the cuff) we would instead use `shaded.com.oracle.oci.javasdk.javax.ws.rs.client.ClientBuilder`.

Additionally, any existing Helidon 2.5.x user who had, say, an OCI [`ClientConfigurator`](https://docs.oracle.com/en-us/iaas/tools/java/2.30.0/com/oracle/bmc/http/ClientConfigurator.html) would have to change that code as well (this is independent of Helidon).

Further, we would instruct users to manually download and manually install the shaded jar [as documented in the OCI SDK documentation](https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/javasdkexamples.htm#:~:text=Third%2DParty%20Dependencies%20and%20Shading), since as of last check [this jar file does not exist in Maven Central](https://github.com/oracle/oci-java-sdk/issues/371#issuecomment-1086331705).

(It also seems to me that any CI/CD setup, Helidon's or a customer's, will need to do this as well on each run unless there's an easier way that I'm not thinking of so there may be some devops-style work here too.)

Next we'll need to make sure our end users understand that in this setup they'll have to use the full shaded jar, even though they're probably only using one or two services out of it, because there aren't shaded versions of the individual OCI service jars.  Either that or maybe there's some way to programmatically break it into pieces while manually installing it into the local Maven repository.

**Comment by ljnelson** [comment]
More notes: @mricken had previously offered to release the shaded jar into Maven Central.  I've pinged him again in oracle/oci-java-sdk#371 to see if that can happen.  I'd quite obviously much rather just fetch a dependency from Maven Central rather than unzipping an artifact, extracting the shaded jar, pre-populating a local Maven repo with it, etc. etc. etc.

**Comment by arjav-desai** [comment]
- We have deprecated our Gen 2/Native OCI integration in 2.x and need to remove it from 3.0 once this change in. 
- We have updated our oci vault example to use this new approach in 2.x but need to update other examples i.e. object storage and ATP to this new approach as well.
- Update docs and README to reflect this change.

All of the above will be done as part of #4480

**Comment by ljnelson** [comment]
More notes to myself.  This comment may be edited frequently.

It is coming up on three months since oracle/oci-java-sdk#371 offered to upload the shaded jar and one month since oracle/oci-java-sdk#410 said it would be prioritized so sadly it looks like we're going to have to do some of this manually, as Romain notes above.

So in our pipeline scripts, for every build, we'll therefore need to:
 * Figure out what version of OCI the project being built depends on (involves something like `mvn -q -N help:evaluate -Dexpression=version.lib.oci -DforceStdout`, which relies on #4483) 
 * Download (only when necessary) the relevant ~721 megabyte zip file (!) containing the entirety of the OCI Java SDK (and its javadocs, and everything else) from Github (e.g. https://github.com/oracle/oci-java-sdk/releases/download/v2.35.0/oci-java-sdk-2.35.0.zip)
 * Extract from it the ~100 MB (!) fully shaded jar (again only when necessary) which lives at, e.g., `shaded/lib/oci-java-sdk-full-shaded-2.35.0.jar`
 * [`mvn install:install-file`](https://maven.apache.org/plugins/maven-install-plugin/install-file-mojo.html) it per [the official OCI instructions](https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/javasdkexamples.htm#:~:text=Third%2DParty%20Dependencies%20and%20Shading) into the pipelines' local maven repository

Then we'll need to:
 * Ensure that any examples we have and any documentation make reference to the manual workaround all of our customers will have to perform in order to use the shaded jar (i.e. point them at [the official OCI documentation](https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/javasdkexamples.htm#:~:text=Third%2DParty%20Dependencies%20and%20Shading) that says they have to download the ~721 MB zip file themselves and extract the ~100 MB shaded jar file themselves and `mvn install:install-file` it into _their_ local Maven repositories and/or project pipelines)

Finally from a coding perspective I'll need to prepare a PR from my private branch that actually uses the shaded artifacts properly.
