### ISSUE TITLE
Helidon support for JDK 18

### ISSUE THREAD

**Issue by Verdent** [oracle/helidon#4128]
We need to verify it is possible to run all of the Helidon components on JDK 18.

**Comment by barchetta** [comment]
I have built and run the 2.5.0 examples and tests against the released Helidon 2.5.0 artifacts using java 18 2022-03-22 and the one problem I found was with EclipseLink not supporting the Java 18 bytecode. This was resolved by #4131 and should be fixed in Helidon 2.5.1.

I'm going to close this issue. If we find  specific bugs with Java 18 then we can open those as specific issues.
