### ISSUE TITLE
Please provide documentation for the use of websocket client in Helidon SE

### ISSUE THREAD

**Issue by lost4git** [oracle/helidon#4234]

**Comment by m0mus** [comment]
Related to #4554

**Comment by spericas** [comment]
We don't provide any detailed documentation for the WebSocket API because it is the standard JSR 356 API (for the same reason we don't provide detailed documentation for JAX-RS). Is there something specific you are looking for? There's also tests and examples in our code base that use WebSocket clients. For example:

https://github.com/oracle/helidon/blob/master/webserver/websocket/src/test/java/io/helidon/webserver/websocket/test/EchoClient.java
