### ISSUE TITLE
Create OpenRewrite template for 2.x -> 3.x project migration

### ISSUE THREAD

**Issue by m0mus** [oracle/helidon#4281]

**Comment by m0mus** [comment]
Won't fix

**Comment by timtebeek** [comment]
Hi @m0mus ; would this be something you'd reconsider for 4.0.0? And would there be anything I can help with?
It seems there's quite some existing migrations you can directly apply already, and building blocks for Helidon specifics.

**Comment by m0mus** [comment]
@timtebeek Actually, we didn't discuss it. Helidon 3.x supports MP 5.0, Helidon 4.0 will support MP 6.0. It may make sense to provide OpenRewrite templates for it. 
Thanks for offering help. How deep is your offer? Is it limited to consultancy and answering question or you can create the migration template and contribute it to Helidon?

**Comment by timtebeek** [comment]
I've not discussed this at work (yet), but I can help setup the basic structure of what you'd need to get started, as it'd be similar to what we have for other frameworks.

If you look to rewrite-micronaut for instance, there's [some scaffolding](https://github.com/openrewrite/rewrite-micronaut/blob/main/build.gradle.kts) to add dependencies to other modules and then a [yaml recipe file](https://github.com/openrewrite/rewrite-micronaut/blob/main/src/main/resources/META-INF/rewrite/micronaut2-to-3.yml) that aggregates both recipes from existing modules, as well as recipes specific to micronaut.

I imagine that starting out it'd be much the same for Helidon, and then gradually diverge as you add custom visitors for specific cases. Some of those will be mere yaml recipes as seen above, others will require a Java visitor for more complex changes. Should not be hard to offer something to begin with, and expand that as needed, hopefully with help from the community. Even an imperfect partial migration might help your users attempt the leap, as you likely want them to.

As for my own contribution to this: I'm not too familiar with Helidon, but seeing this issue here thought to reach out and offer some guidance, as it could benefit both your users, and potentially ours as well for the common migration steps.

Let me know if and how you'd like to proceed, and maybe [swing by our Slack](https://join.slack.com/t/rewriteoss/shared_invite/zt-nj42n3ea-b~62rIHzb3Vo0E1APKCXEA) if you'd want to talk some more.

**Comment by timtebeek** [comment]
Here's another recent [sample migration for AxonFramework](https://github.com/AxonFramework/AxonFramework/pull/2597), in case it helps to see a minimal reference to copy. Just hoping to be helpful here. :)
