### ISSUE TITLE
Issue to execute JNoSQL with Helidon version MP 2.4.1

### ISSUE THREAD

**Issue by otaviojava** [oracle/helidon#4424]
## Environment Details
* Helidon Version: 2.4.1
* Helidon SE or Helidon MP: Helidon MP
* JDK version: Java 11 or Java 17
* OS: Linux
* Docker version (if applicable):

----------

## Problem Description

I have an issue executing JNoSQL with Helidon version 2.4.1 or higher.

I created a project from either [Microprofiler Starter](https://start.microprofile.io/) or [Maven Architypes](https://helidon.io/docs/v2/#/mp/guides/02_quickstart) and then add these dependencies:

```xml
      <dependency>
            <groupId>org.eclipse.jnosql.mapping</groupId>
            <artifactId>mapping-document</artifactId>
            <version>${jakarta.nosql.version}</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jnosql.communication</groupId>
            <artifactId>mongodb-driver</artifactId>
            <version>${jakarta.nosql.version}</version>
        </dependency>
```
I expected to work such as in the previous version, [1.4](https://github.com/soujava/jnosql-rc1-sample), however, it stopped working.

I have those projects where both run with extension and only one works, however, both are using the same extension event: [ProcessAnnotatedType](https://github.com/eclipse/jnosql/blob/master/mapping/mapping-core/src/main/java/org/eclipse/jnosql/mapping/reflection/ClassMappingExtension.java)

https://github.com/architects4j/helidon-challange-skeleton

This project works fine on [Java SE](https://github.com/JNOSQL/demos/tree/main/demo-java-se/mongodb) or with [Payara](https://github.com/architects4j/payara-fastlane-demos/tree/main/nosql).

**Comment by otaviojava** [comment]
I believe it is related to both: 
https://github.com/oracle/helidon/issues/2431 and https://github.com/oracle/helidon/issues/1648

**Comment by ljnelson** [comment]
Could you please describe the error you are encountering?

**Comment by otaviojava** [comment]
Hey @ljnelson 
Helidon did not execute the JNoSQL extensions.


When I run this [project](https://github.com/architects4j/helidon-challange-skeleton/tree/main/acme-store-service-2)

```
2022.06.22 18:18:55 INFO io.helidon.common.LogConfig !thread!: Logging at initialization configured using classpath: /logging.properties
2022.06.22 18:18:55 INFO org.jboss.weld.Version !thread!: WELD-000900: 3.1.6 (Final)
2022.06.22 18:18:55 INFO org.jboss.weld.Bootstrap !thread!: WELD-ENV-000020: Using jandex for bean discovery
2022.06.22 18:18:55 INFO org.jboss.weld.Bootstrap !thread!: WELD-000101: Transactional services not available. Injection of @Inject UserTransaction not available. Transactional observers will be invoked synchronously.
2022.06.22 18:18:55 INFO org.jboss.weld.Event !thread!: WELD-000411: Observer method [BackedAnnotatedMethod] private io.helidon.microprofile.openapi.OpenApiCdiExtension.processAnnotatedType(@Observes ProcessAnnotatedType<X>) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
2022.06.22 18:18:55 INFO org.jboss.weld.Event !thread!: WELD-000411: Observer method [BackedAnnotatedMethod] public org.glassfish.jersey.ext.cdi1x.internal.ProcessAllAnnotatedTypes.processAnnotatedType(@Observes ProcessAnnotatedType<?>, BeanManager) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
2022.06.22 18:18:56 INFO org.jboss.weld.Bootstrap !thread!: WELD-ENV-002001: Weld SE container 3da2625e-5c29-4f3c-9f5c-94bcf9d41c82 shut down
Exception in thread "main" org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type ProductRepository with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject private com.architects4j.workshop.microstream.helidon.product.ProductResource.repository
  at com.architects4j.workshop.microstream.helidon.product.ProductResource.repository(ProductResource.java:0)
```

**Comment by ljnelson** [comment]
Is this (https://github.com/eclipse/jnosql-mapping-extension/blob/8dc0bfff6a7a4c472b7a9bf4f6cb82d8883cadb2/mongodb-extension/src/main/resources/META-INF/services/javax.enterprise.inject.spi.Extension#L15) a typo?

**Comment by otaviojava** [comment]
Hey, @ljnelson it is a typo, thank you.

But on this sample, we don't use this project.

Basically, we use those projects:

- https://github.com/eclipse-ee4j/nosql
- https://github.com/eclipse/jnosql
- https://github.com/eclipse/jnosql-communication-driver/tree/master/mongodb-driver

**Comment by ljnelson** [comment]
Notes to myself as I try to understand this.  I will edit this comment as I learn more, so it will keep changing.

First, the OP [adds the following dependency](https://github.com/architects4j/helidon-challange-skeleton/blob/18e9a256c86d8b7add3a775a7308449eaa37ebe1/acme-store-service-2/pom.xml#L37-L41) (see comments above):
```xml
<dependency>
    <groupId>org.eclipse.jnosql.mapping</groupId>
    <artifactId>mapping-document</artifactId>
    <version>${jakarta.nosql.version}</version> <!-- 1.0.0-b4 as of this writing; see https://github.com/architects4j/helidon-challange-skeleton/blob/18e9a256c86d8b7add3a775a7308449eaa37ebe1/acme-store-service-2/pom.xml#L23 -->
</dependency>
```

That project contains the following service provider file:

https://github.com/eclipse/jnosql/blob/1.0.0-b4/mapping/mapping-document/src/main/resources/META-INF/services/javax.enterprise.inject.spi.Extension

It references the following extension:

https://github.com/eclipse/jnosql/blob/1.0.0-b4/mapping/mapping-document/src/main/java/org/eclipse/jnosql/mapping/document/spi/DocumentExtension.java

This extension observes all annotated types (though I'm not sure why it doesn't observe simply `ProcessAnnotatedType<Repository>` since it appears [that is all it is interested in](https://github.com/eclipse/jnosql/blob/1.0.0-b4/mapping/mapping-document/src/main/java/org/eclipse/jnosql/mapping/document/spi/DocumentExtension.java#L51-L62)).

Then the OP [adds the following dependency](https://github.com/architects4j/helidon-challange-skeleton/blob/18e9a256c86d8b7add3a775a7308449eaa37ebe1/acme-store-service-2/pom.xml#L42-L46) (see comments above):
```xml
<dependency>
    <groupId>org.eclipse.jnosql.communication</groupId>
    <artifactId>mongodb-driver</artifactId>
    <version>${jakarta.nosql.version}</version> <!-- 1.0.0-b4 as of this writing; see https://github.com/architects4j/helidon-challange-skeleton/blob/18e9a256c86d8b7add3a775a7308449eaa37ebe1/acme-store-service-2/pom.xml#L23 -->
</dependency>
```

The Maven coordinates for this dependency are here: https://search.maven.org/artifact/org.eclipse.jnosql.communication/mongodb-driver/1.0.0-b4/jar

There is no `<source>` element in this `pom.xml` or its parents that results in a project that contains a `mongodb-driver` artifact, so it must live somewhere else.

Fortunately the sources themselves are in Maven Central: https://repo1.maven.org/maven2/org/eclipse/jnosql/communication/mongodb-driver/1.0.0-b4/mongodb-driver-1.0.0-b4-sources.jar

From searching Github for an occurrence of `OldMongoDBDocumentConfigurations` (a class name in the sources that seems pretty unique), we can see that the source code for the `mongodb-driver` artifact lives here: https://github.com/eclipse/jnosql-communication-driver/tree/1.0.0-b4/mongodb-driver

There are no additional portable extensions in this project.

The OP claims that the (sole) portable extension does not execute because the error output from Weld indicates that there is an injection point expecting a `ProductRepository` that is unsatisfied.  (Presumably the portable extension exists to satisfy extension points like this.)

The OP expects [logging information from `DocumentExtension.java`'s `AfterBeanDiscovery` observer](https://github.com/eclipse/jnosql/blob/1.0.0-b4/mapping/mapping-document/src/main/java/org/eclipse/jnosql/mapping/document/spi/DocumentExtension.java#L71-L73) to be output, but apparently sees no such output.  He assumes that the lack of output means that (a) an instance of `DocumentExtension` is never created by the container, (b) its `ProcessAnnotatedType` observer never runs and (c) its `AfterBeanDiscovery` observer never runs.

All of this could of course be because the log level is not set appropriately; we'll have to make sure that's the case.

**Comment by otaviojava** [comment]
Thank you @ljnelson

**Comment by tjquinno** [comment]
@otaviojava Some more information on why adding the Jackson dependency helps...

As you have no doubt noticed, Helidon's OpenAPI support layers on some SmallRye OpenAPI components. Although SmallRye defaults to using Jackson, it also permits callers to provide their own `AnnotationScannerExtension` to do parsing however they want, using whatever libraries they want. Helidon does just that.

Your use case has revealed a place in SmallRye's code that uses Jackson _even if_ the caller provides the extension. 

I have opened https://github.com/smallrye/smallrye-open-api/issues/1161 about this.

As you've done, adding Jackson yourself to the dependencies sidesteps this problem for your Helidon app.
