### ISSUE TITLE
Filters mixed-up between multiple apps

### ISSUE THREAD

**Issue by martin-sladecek** [oracle/helidon#4615]
## Environment Details
* Helidon Version: 2.5.1
* Helidon MP
* JDK version: 17
* OS: Linux
* Docker version (if applicable):

----------

## Problem Description
Seems like an filter from a different jersey application is sometimes applied.

## Steps to reproduce
Run the test in the attached project.
[quickstart-mp2.zip](https://github.com/oracle/helidon/files/9197034/quickstart-mp2.zip)

**Comment by martin-sladecek** [comment]
[quickstart-mp2.zip](https://github.com/oracle/helidon/files/9191380/quickstart-mp2.zip)

**Comment by spericas** [comment]
As you know the basic Application isolation provided by Helidon relies on the set of classes returned by `getClasses`. In this example, isolation is seeked by dynamically attempting to register filters using a feature. All that part is controlled by Jersey and completely outside of Helidon's control. Jersey is likely registering all filters in the same injection manager, and thus provides no isolation.

If the `getClasses` form of isolation is not sufficient (because it needs to be more dynamic) then you'd need to inspect the context of an individual `ServerRequest` and avoid running the logic depending on which application is "active". You can `@Context`-inject `ServerRequest` and then inspect the context as follows:

```
        Application app = serverRequest.context().get(Application.class).get();
```

There's not much else for us to do at this time.

**Comment by mkuchtiak** [comment]
I found a workaround for this to set:
**server.single-injection-manager=true**
in resources/META-INF/microprofile-config.properties

but, however, this is not recommended setting, right ?

**Comment by spericas** [comment]
Can you confirm that this new access would cover your use case?

```
    public boolean configure(FeatureContext context) {
        Application app = Contexts.context().flatMap(c -> c.get(Application.class)).orElse(null);
        System.out.println("app = " + app);

        // ...
        return true;
    }
```

**Comment by martin-sladecek** [comment]
Yes, I think this should be sufficient. Will the same apply to AutoDiscoverable?

**Comment by spericas** [comment]
PR #4745

**Comment by spericas** [comment]
Closing this issue at this time. We have found a workaround that uses the feature in PR #4745 (targeted for 2.5.3).
