### ISSUE TITLE
 SAML provider implementation for Helidon MP

### ISSUE THREAD

**Issue by vjaiswal1** [oracle/helidon#4674]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version:
* Helidon MP
* JDK version:11
* OS:
* Docker version (if applicable):

----------

## Problem Description
Hi Team,
We are migrating existing services to helidon.
in existing code , we encode SAMLObject via HTTPRedirectDeflateEncoder & redirect the response via HttpServletResponse.
We need to remove dependency of HttpServletResponse & HttpServletRequest while encoding & decoding, n use io.helidon.webserver.ServerResponse , io.helidon.webserver.ServerRequest.
attached the existing code snapshot.
final HTTPRedirectDeflateEncoder encoder = new HTTPRedirectDeflateEncoder();
encoder.setHttpServletResponse(httpResponse);
encoder.setMessageContext(messageContext);
try {
  encoder.initialize();
  encoder.encode();
}
note->  httpResponse is HttpServletResponse,  Servlet not to be used for request & response.

**Comment by vjaiswal1** [comment]
@m0mus Please priortize it.

**Comment by tomas-langer** [comment]
Hello,
 can you please
1. share which library you use for your SAML integration? Maybe there is an integration for JAX-RS that uses ContainerRequest instead of servlet (we do not support servlet)
2. share the use case - in general, modern microservices (and on premises solutions) depend on Open IDConnect together with OAuth. This is what Helidon supports and provides integration for. What solution do you use that SAML is mandated? 

We currently do not have a SAML integration for Helidon Security, and the above would help us decide whether we want to implement such a component as part of Helidon security, or we would guide you on how to integrate it yourself.

**Comment by tomas-langer** [comment]
As there was no feedback from the user, I am closing this issue as will not fix. 
Feel free to re-open if you can provide answers to the questions posted in my previous comment (thanks!)
