### ISSUE TITLE
BareResponse requests Long.MAX_VALUE from writer publisher

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#473]
When we create a custom writer, we return a publisher. In the method `onSubscribe`, I can see that webserver requests Long.MAX_VALUE.
This may cause major issues when the writer can write huge amount of data.
E.g. when reading bytes from a file or result set from a database, we may just push data into memory that should not be there.
I would expect the `BareResponseImpl` to request a few `DataChunk`s and when it pushes them over the network, it would request more.
In my understanding, this is the core of the "reactive nonblocking implementation with push back support"...

**Comment by spericas** [comment]
As I said, I think there's a big misconception about the need to request one chunk at a time for the purpose of _flow control_: subscribers have full support for flow control since `onNext` cannot be called in parallel. 

It is certainly useful to request individual chunks if this _reduces the amount of initial work done by the publisher_, work that would otherwise be wasted. Maybe this is this issue, I'm not sure. What is the line number of that `onSubscribe`? Responses should push chunks (lambdas) to be (asynchronously) executed by the Netty NIO event loop. 

There are many cases where requesting a chunk at a time is actually slower because of the additional housekeeping that is required.

**Comment by tomas-langer** [comment]
The problem I see here is if the producer is faster than the consumer. If you decide to buffer the data, you would use too much memory.
This basically requires the publisher to "be nice" and if requested a lot of data, actually wait on the "onNext" method before buffering more.
Not sure this is better. Also this brings in a blocking call (onNext is blocking when it cannot consume another chunk).

**Comment by spericas** [comment]
Looking at the code, the data passed to the `onNext` is already in a buffer. It is that very same buffer (wrapped) that is pushed to the Netty IO loop for writing. The writing operation is async, so there is no blocking call in `BareRequestImpl::onNext`. 

When using our JSON providers, all the data is written in a single buffer (single call to `onNext`). I suppose, because the `onNext` is async, that it is possible for some very fast producer to overrun the Netty IO loop; but if that every happens, the app is likely already in trouble. Waiting for each chunk to be delivered to the network before requesting the next one will have a negative impact on performance. I really don't think there's anything we need to do here.

**Comment by spericas** [comment]
Following up on the last comment, most of our writers in fact execute a single call to `onNext`, especially those that bridge message body writers in Jersey.

 Perhaps this is something we can revisit when we provide a reactive DB implementation, but even then unless DB data is streamed in chunks to the client (using some sort of streaming format), there isn't a lot of value in changing subscription requests IMO.

**Comment by spericas** [comment]
After some discussions with @tomas-langer and @batsatt, I'm re-opening this issue. Tomas is working on the reactive DB stuff, so this is needed now.

**Comment by spericas** [comment]
I have experimented with an algorithm to request chunks progressively in order to better handle large data sets while minimizing overhead for more _normal_ cases. I'd like to try it out with the Helidon DB database code once it becomes available before submitting a PR. New algorithm is available here https://github.com/spericas/helidon/tree/flow-control

**Comment by spericas** [comment]
PR #700
