### ISSUE TITLE
Helidon JPA should be able to pick up a Hand build EntityManagerFactory

### ISSUE THREAD

**Issue by lscoughlin** [oracle/helidon#4743]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 2.x 3.x
*  Helidon MP
* JDK version: 17+
* OS: Unix
* Docker version (if applicable): N/A

----------

## Problem Description
In some scenarios I need to hand roll a JPA EntityManagerFactory. I should be able to have Helidon JPA integration pickup this hand rolled entity manager factory in some way.

## Steps to reproduce
1. Hand roll an entity manager factory
3. watch it be useless.

## Suggestion
Maybe add an EntityManagerFactoryProvider interface that implements Supplier<EntityManagerFactory> and try and service load it in the jpa-extension?

**Comment by ljnelson** [comment]
Do you have additional requirements (I assume yes)?

Here are some ways to get a handle on an `EntityManagerFactory` that may help.  Or not.

To acquire a simple application-managed `EntityManagerFactory`:

```java
// Write your own one-liner producer method to make an application-managed EMF
@Produces
@SomeScopeYouWant
private static EntityManagerFactory makeApplicationManagedEntityManagerFactory() {
  return Persistence.createEntityManagerFactory("somePersistenceUnitName");
}
```

Since it's application-managed, according to the specification, you can do pretty much whatever you want; the rules are your own.  Obviously bear in mind threadsafety, error handling, transaction rollback, etc. etc.

To acquire a container-managed `EntityManagerFactory` built according to the rules of JPA:

```java
// Inject a container-managed EMF following the rules of JPA's container-managed mode
@PersistenceUnit
private EntityManagerFactory containerManagedEmf;
```

These are made under the covers by the JPA-defined integration SPI [`PersistenceProvider#createContainerEntityManagerFactory(PersistenceUnitInfo, Map)`](https://jakarta.ee/specifications/persistence/2.2/apidocs/javax/persistence/spi/persistenceprovider#createContainerEntityManagerFactory(javax.persistence.spi.PersistenceUnitInfo,java.util.Map)) supplied by the JPA implementor (Eclipselink, Hibernate, etc.).

**Comment by ljnelson** [comment]
(Incidentally: the service-loading bit you suggest is already present in the specification, sort of: if you implement your own `PersistenceProvider` then it should be used as the default (instead of Hibernate or Eclipselink; many people implement this to wrap their standard facilities, maybe in the ways you have in mind).)

**Comment by ljnelson** [comment]
May I close this, since there are various facilities within JPA itself to help you accomplish what you want to do?

**Comment by lscoughlin** [comment]
Yeah I think so - overriding the PersistenceProvider accomplishes my need I think.
