### ISSUE TITLE
Can't create custom producer/alternative for @ConfigProperty

### ISSUE THREAD

**Issue by stasha** [oracle/helidon#536]
Can't create custom producer/alternative for @ConfigProperty

## Environment Details
* Helidon Version: 1.0.1
* Helidon MP
* JDK version: jdk1.8.0_172
* OS: Linux Mint
* Docker version (if applicable):

----------

## Problem Description
When custom producer/alternative for @ConfigProperty is "registered" it fails with exception.
When @ConfigProperty is removed from producer and from field it works correctly.

### Exception
```
org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type String with qualifiers @Named @ConfigQualifier @ConfigProperty
  at injection point org.jboss.weld.bootstrap.events.configurator.InjectionPointConfiguratorImpl$ImmutableInjectionPoint@2b120e4
  at info.stasha.testosterone.jersey.junit4.helidon.HelidonTest.currency2(HelidonTest.java:0)
WELD-001475: The following beans match by type, but none have matching qualifiers:
  - Producer Method [String] with qualifiers [@Any @ConfigProperty @Named] declared as [[BackedAnnotatedMethod] @Produces @Named @ConfigProperty public info.stasha.testosterone.cdi.PropertyConfigProducer.getValue(InjectionPoint)],
  - Producer Method [String] with qualifiers [@JaxRsParamQualifier @Any] declared as [[UnbackedAnnotatedMethod] @Produces @JaxRsParamQualifier public org.glassfish.jersey.ext.cdi1x.internal.CdiComponentProvider$JaxRsParamProducer.getParameterValue(InjectionPoint, BeanManager)]
```

### Producer
```
@Dependent
public class PropertyConfigProducer {

    @Produces
    @Named("test")
    @ConfigProperty
    public String getValue(InjectionPoint ip) {
        return "test";
    }
}
```
```    
@Inject
@Named("test")
@ConfigProperty(name = "currency2", defaultValue = "eur")
private String currency2;
```

**Comment by ljnelson** [comment]
There are a couple things seemingly going on here.

The first is definitely our bug; it appears that the current mechanism for injecting `@ConfigProperty` values does so by scanning all injection points, and maybe (?) adding `@ConfigQualifier`—an internal annotation?—to them programmatically.  It would of course follow from this that indeed no external user could simply produce a `@Named @ConfigProperty String` because they would also somehow have to know to instead produce a `@Named @ConfigProperty @ConfigQualifier String`.  Perhaps our internals attempt to catch even this case and fail, or perhaps this case was not accounted for; I'm not sure.

The second is more of a usage issue: it's not clear why one would ever want to combine `@Named("something")` with `@ConfigProperty(name = "something")`, as the value of the `@Named` annotation and the value of the `name` element of the `@ConfigProperty` annotation are redundant.

In general I personally feel our configuration property injection mechanism, a part of our MicroProfile Config implementation, could be much simpler than it is, so I'll look into this to see what can be done.
