### ISSUE TITLE
ServerResponse in Helidon SE should support Publisher<Thing>

### ISSUE THREAD

**Issue by spericas** [oracle/helidon#637]
The `ServerResponse` interface in SE supports sending `Publisher<DataChunk>`. When handling large data sets of `Thing`'s, it would be convenient to send them directly without the _application developer_ having to convert them to `DataChunk`'s one by one. 

This task will explore support for these type of publishers and what additions to the API would be required to support this. One challenge relates to the serialization of these streams of `Thing`'s. In the JSON case, should we use only arrays? What about better streaming formats with support for _framing_?

**Comment by tomas-langer** [comment]
We would need a way to tell the webserver the type of `Thing`.
If we just register a `Publisher<Thing>` the type is lost due to type erasure.
Another question is how to decide what type of output should be used - based on the existing writer support (e.g. if we have `JSON-B` registered, then it should be used for serializing the instances into bytes) - so this would require us to add support to our writers to handle streams of `Things`, or it would require a brand new type of `Stream of things` writers?

**Comment by spericas** [comment]
https://github.com/oracle/helidon/pull/665

**Comment by spericas** [comment]
Now in scope of @romain-grecourt's work.
