### ISSUE TITLE
Consider using Content-Length instead of chunked encoding

### ISSUE THREAD

**Issue by spericas** [oracle/helidon#750]
Use of chunked encoding is unnecessary and does not result in the best performance on normal JSON/text payloads. We should consider computing a payload length and using `Content-Length` instead. This requires some changes to our tests that assume chunked encoding.

**Comment by romain-grecourt** [comment]
From BareResponseImpl:

```java
        if (keepAlive) {
            if (status.code() != Http.Status.NO_CONTENT_204.code()) {
                HttpUtil.setTransferEncodingChunked(response, true);
            }
            // Add keep alive header as per:
            // - http://www.w3.org/Protocols/HTTP/1.1/draft-ietf-http-v11-spec-01.html#Connection
            response.headers().set(HttpHeaderNames.CONNECTION, HttpHeaderValues.KEEP_ALIVE);
        }
```

**Comment by spericas** [comment]
@romain-grecourt Can you elaborate on your comment? :)

**Comment by romain-grecourt** [comment]
Just highlighted the code current code in Helidon that activates transfer encoding.

Also from the netty [javadocs](https://netty.io/4.0/api/io/netty/handler/codec/http/HttpResponseDecoder.html): 

maxChunkSize | The maximum length of the content or each chunk. If the content length exceeds this value, the transfer encoding of the decoded response will be converted to 'chunked' and the content will be split into multiple HttpContents. If the transfer encoding of the HTTP response is 'chunked' already, each chunk will be split into smaller chunks if the length of the chunk exceeds this value.
-- | --

Seems that we'd have to tune maxChunkSize according to the content length.

Thinking-out-loud: Given that the payload is consumed by `BareResponseImpl` with a subscriber there is no easy way to get the content-length right ? Maybe the subscriber could accumulate the data-chunks until onComplete so that the content-length can be computed.

I presume that this would have to be optional and configureable on the response, maybe the media support class can do that at the same time it registers the reader/writer but that is without knowing the actual payload. Maybe we could event go further and give that ability to the writer since it converts the entity to `Publisher<DataChunk>` so it may have a way to derive the content-length early.

Maybe we could also think of a "buffer until threshold" mechanism in the response.  I.e Accumulate at most N bytes to achieve content-length, otherwise do chunked.

**Comment by tomas-langer** [comment]
Chunked encoding exists for cases when payload size is unknown.
You do not need to limit "content-length" responses by size - even a 1GB file can be sent without chunked encoding, as long as you know the size in advance.
Usually the decision is done based on the presence of `Content-Length` header being set by the user (or in our cases we could do it also when user sends `String`, `JsonObject` and other objects that are in-memory already and we can easily transform them into bytes and measure the size).

**Comment by romain-grecourt** [comment]
Our underlying implementation is reactive so we'd have to implement something that does not rely on the entity, otherwise this means we'd have to carry that information from the media writer down to BareResponseImpl.

Having a buffer until threshold mechanism, similar to what's described on the Netty javadocs seems viable.

**Comment by spericas** [comment]
PR #773
PR #783
PR #795
