### ISSUE TITLE
gRPC missing module-info.java

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#759]
gRPC modules are missing `module-info.java`

**Comment by thegridman** [comment]
There is an issue with this because out of the box grpc-java has split package issues so you cannot use it with Java 9 modules. The solution suggested on the GitHub issues that mention this in grpc-java is to re-package grpc-java by shading into a single jar, with either an automatic module name or a `module-info.java` file added. 

To make this work in Helidon we would need to do something like introduce a new sub-module under the helidon-grpc-project that does this repackaging and produces a Helidon grpc-java module. This would be the only module that has a dependency on the real grpc-java jars. The rest of the Helidon modules that currently depend on grpc-java would depend on this new module instead and could then all have `module-info.java` files added.

It is not ideal but is the only solution available as grpc-java have no intention reorganizing their jars until maybe grpc-java 2.0.

**Comment by thegridman** [comment]
After discussing the approach on a call with Tomas I have done the changes and created a PR https://github.com/oracle/helidon/pull/789
