### ISSUE TITLE
Can not load application.yaml from assembled fat jar

### ISSUE THREAD

**Issue by XuefengWu** [oracle/helidon#77]
## Environment Details
* Helidon Version: 0.10.0
* Helidon SE 
* JDK version: 1.8
* OS: MacOS

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
Helidon application can load application.yaml when package app jar, but when package a fat jar,
it can not load.

## Steps to reproduce
add assembly to helidon/examples/helidon-quickstart-se/pom.xml 

assembly a fat: pom.xml
```
     <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <configuration>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                    <archive>
                        <manifest> 
                            <mainClass>${mainClass}</mainClass>
                        </manifest>
                    </archive>
                </configuration>
                <executions>
                    <execution>
                        <id>simple-command</id>
                        <phase>package</phase>
                        <goals>
                            <goal>attached</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```
run maven package and assemble a fat jar
```
mvn package
```

then run this fat jar
```
java -jar target/quickstart-se-jar-with-dependencies.jar
```

it can not load application.yaml and run on a random port.

**Comment by XuefengWu** [comment]
The fat jar does include the application.yaml

**Comment by barchetta** [comment]
I was able to reproduce this as described by the submitter. The obvious things check out: the application.yaml is in the fat jar and contains what it should, the java.classpath is set to the fat jar, but no config is loaded.

**Comment by ljnelson** [comment]
Narrowed the problem down to media type detection.

The problem is related to the `null` or empty return value of the `getMediaType()` method as invoked in this method when `resource` is `application.yaml`:

https://github.com/oracle/helidon/blob/0676914f85751b0ebbc66b2fbb9752293b9da966/config/config/src/main/java/io/helidon/config/internal/ClasspathConfigSource.java#L109-L128

`resource` is `application.yaml` here instead of, say, `jar:/...!/application.yaml` because of some earlier method I've lost track of that attempts to do the equivalent of `Paths.get(jarUrlStringRepresentation)` which results in a `FileSystemNotFoundException` which is subsequently swallowed.  I have to track that down again.  More as I find it.

**Comment by ljnelson** [comment]
Well, fundamentally this line:

https://github.com/oracle/helidon/blob/2c7689019fd40b2b6fce762fd906ee97aa310bb6/config/config/src/main/java/io/helidon/config/internal/ClasspathSourceHelper.java#L61

…will fail if handed something that is not a filesystem path (such as a `String` representation of a `jar:` URI, as in this case).  The failure is gracefully handled in several places.  For example, here's one place where the failure is caught and logged (there are others that follow the same pattern):

https://github.com/oracle/helidon/blob/2c7689019fd40b2b6fce762fd906ee97aa310bb6/config/config/src/main/java/io/helidon/config/internal/ClasspathSourceHelper.java#L67-L77

As you can see, a default value in this case is used (the epoch).

We finally get here:

https://github.com/oracle/helidon/blob/0676914f85751b0ebbc66b2fbb9752293b9da966/config/config/src/main/java/io/helidon/config/internal/ClasspathConfigSource.java#L125-L127

When the resource name is `application.yaml`, the `InputStreamReader` is nevertheless properly "hooked up" to the `application.yaml` entry in the fat jar and is capable of reading it.  So we're sort of good so far: although `Paths.get()` has failed multiple times they've all been handled.  But then we run into that `getMediaType()` call.  Ultimately that lands us here:

https://github.com/oracle/helidon/blob/2c7689019fd40b2b6fce762fd906ee97aa310bb6/config/config/src/main/java/io/helidon/config/ConfigHelper.java#L175-L192

There is, at this point, only one installed detector, and it does this:

https://github.com/oracle/helidon/blob/2c7689019fd40b2b6fce762fd906ee97aa310bb6/config/config/src/main/java/io/helidon/config/internal/ConfigFileTypeDetector.java#L27-L36

That means that since the `Path` that is passed in is simply "`application.yaml`" it is quite obviously not a properties file, so this detector returns `null`.

When the detector returns `null`, then at the following point we have a `Content` that has a `null` media type:

https://github.com/oracle/helidon/blob/2c7689019fd40b2b6fce762fd906ee97aa310bb6/config/config/src/main/java/io/helidon/config/spi/AbstractParsableConfigSource.java#L58

This ultimately leads to a `ConfigException` being thrown here:

https://github.com/oracle/helidon/blob/2c7689019fd40b2b6fce762fd906ee97aa310bb6/config/config/src/main/java/io/helidon/config/spi/AbstractParsableConfigSource.java#L100

This is then caught here:

https://github.com/oracle/helidon/blob/2c7689019fd40b2b6fce762fd906ee97aa310bb6/config/config/src/main/java/io/helidon/config/spi/AbstractSource.java#L207-L217

…and is logged at the `CONFIG` and `FINE` levels:

https://github.com/oracle/helidon/blob/2c7689019fd40b2b6fce762fd906ee97aa310bb6/config/config/src/main/java/io/helidon/config/spi/AbstractSource.java#L253-L258

Finally after all this an empty `Optional` is returned as though the `ConfigSource` in question didn't have any data:

https://github.com/oracle/helidon/blob/2c7689019fd40b2b6fce762fd906ee97aa310bb6/config/config/src/main/java/io/helidon/config/spi/AbstractSource.java#L217

I'm not sure from this huge journey where the bug actually lies.  Although `Paths.get(locationOfApplicationYamlWithinFatJar)` fails many, many times along this code path (with every invocation of `getTimestamp()`, as an arbitrary example), it seems to me that media type detection of, exactly, "`application.yaml`" should work.  Maybe there's a way to affect what media type detectors are installed?  Not sure.

Having said _that_, a better fix might be to see if we can do away with the `FileSystemNotFoundException` in the first place so that `Path` instances actually reflect true paths even in the case of `jar:` URI references.  I am not enough of an expert on the very complicated and sophisticated config subsystem to know if this is a good idea or a bad one.

**Comment by ljnelson** [comment]
Another thing I noticed is that after applying the `pom.xml` changes that @XuefengWu indicated, the `META-INF/services/java.nio.file.spi.FileTypeDetector` file has only the following line:

    io.helidon.config.internal.ConfigFileTypeDetector

This means that a YAML file in this fat jar will never have its media type detected because there is no `FileTypeDetector` registered to be able to detect the media type.

This may or may not be a result of what the `maven-assembly-plugin` does when it merges service provider files.  For example, I notice that the `pom.xml` excerpt above does _not_ include a container descriptor handler to merge service provider files.  You can read more about container descriptor handlers and how to set them up [in the official Maven documentation](https://maven.apache.org/plugins/maven-assembly-plugin/examples/single/using-container-descriptor-handlers.html).

I'll try running the example again with @XuefengWu's changes **as well as** a container descriptor handler to merge service provider files; my guess is that the resulting single `META-INF/services/java.nio.file.spi.FileTypeDetector` file in the resulting fat jar will have more than one line in it.

**Comment by ljnelson** [comment]
That fixed it.

Specifically:
* Create an assembly descriptor in `src/main/assembly` named `jar-with-deps-merge-services.xml`.  It should look like this:
```
    <?xml version="1.0" encoding="UTF-8"?>
    <assembly xmlns="http://maven.apache.org/plugins/maven-assembly-plugin/assembly/1.1.0" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/plugins/maven-assembly-plugin/assembly/1.1.0 http://maven.apache.org/xsd/assembly-1.1.0.xsd">
    <!-- copied from jar-with-dependencies (http://maven.apache.org/plugins/maven-assembly-plugin/descriptor-refs.html#jar-with-dependencies) -->
      <id>jar-with-deps-merge-services</id>
      <formats>
        <format>jar</format>
      </formats>
      <includeBaseDirectory>false</includeBaseDirectory>
      <containerDescriptorHandlers>
        <containerDescriptorHandler>
          <handlerName>metaInf-services</handlerName>
        </containerDescriptorHandler>
      </containerDescriptorHandlers>
      <dependencySets>
        <dependencySet>
          <outputDirectory>/</outputDirectory>
          <useProjectArtifact>true</useProjectArtifact>
          <unpack>true</unpack>
          <scope>runtime</scope>
        </dependencySet>
      </dependencySets>
    </assembly>
```
* Use version 3.1.0 of the `maven-assembly-plugin`.  Helidon does not currently assign a default version for this plugin, so you are currently using 2.2-beta-5, which is ancient and which does not support merging service provider files.
* In your `<plugin>` element, refer to the descriptor you just created:
```
           <!-- See issue #77 -->
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.1.0</version>
                <configuration>
                    <descriptors>
                        <descriptor>src/main/assembly/jar-with-deps-merge-services.xml</descriptor>
                    </descriptors>
                    <!--
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                    -->
                    <archive>
                        <manifest> 
                            <mainClass>${mainClass}</mainClass>
                        </manifest>
                    </archive>
                </configuration>
                <executions>
                    <execution>
                        <id>simple-command</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                            <!--
                            <goal>attached</goal>
                            -->
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <!-- End of issue #77 changes -->
```
* Since you changed the name of the descriptor, your jar file will have a different name.  So now to run your fat jar you do:
```
java -jar target/quickstart-se-jar-with-deps-merge-services.jar
```
When you do all of this, you will find that the application comes up on port 8080:
```
$ java -jar target/quickstart-se-jar-with-deps-merge-services.jar
[DEBUG] (main) Using Console logging
2018.09.22 15:00:43 INFO io.netty.util.internal.PlatformDependent Thread[main,5,main]: Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system instability.
2018.09.22 15:00:43 INFO io.helidon.webserver.netty.NettyWebServer Thread[nioEventLoopGroup-2-1,10,main]: Channel '@default' started: [id: 0xb95ccfb9, L:/0:0:0:0:0:0:0:0:8080]
WEB server is up! http://localhost:8080
```

I will leave this bug open for the time being so that @barchetta and others can decide whether in addition we want to clean up `Path` handling (and the many exceptions that are thrown and caught during routine configuration assembly—seems expensive, performance-wise).  But otherwise the problem lies in assembling the fat jar, not within Helidon itself.

**Comment by barchetta** [comment]
I think this might be the last straw for using `java.nio.file.spi.FileTypeDetector`.  Too flexible and brittle for our simple use case (and it has caused problems before).

**Comment by ljnelson** [comment]
I don't have an opinion on `FileTypeDetector` one way or the other, but the usage of that class wasn't really the issue here.  This was, at root, a problem with the usage of the `maven-assembly-plugin`.  Once those service providers were properly registered everything worked fine.

My chief concern in this issue is with the repeated invocation of code that generates exceptions only to catch them and substitute a default value; that's expensive at the very least.

**Comment by romain-grecourt** [comment]
IIRC the main issue we had was related to maven and the isolated classloader that was making it impossible to lookup the FileTypeDetector services.

**Comment by romain-grecourt** [comment]
Anyway the fix is to merge the META-INF/services jar files like Laird described.
The maven-shade-plugin can also be used for that.

**Comment by vinodpahuja** [comment]
> Anyway the fix is to merge the META-INF/services jar files like Laird described.
> The maven-shade-plugin can also be used for that.

maven-shade-plugin not working. see https://github.com/oracle/helidon/issues/1358
