### ISSUE TITLE
Context.Builder.generateId() use of UUID causes contention under load

### ISSUE THREAD

**Issue by batsatt** [oracle/helidon#829]
A JFR recording under load shows contention for the lock used in random number generation:
 
![image](https://user-images.githubusercontent.com/4099370/60827773-cfb49d00-a165-11e9-9555-5834045b99c6.png)

Some other mechanism for creating the id should be found.

**Comment by tomas-langer** [comment]
Hello Bryan,
 could you please point me to the sources of your application? I have tried this with our quickstart and this branch in id generation is never used. I need to investigate why it uses the UUID instead of counters defined.

**Comment by tomas-langer** [comment]
see `Context` lines 183-190

**Comment by tomas-langer** [comment]
I have identified the problem, investigating possible solutions.
The problem comes when `ListContextualRegistry` from WebServer is used as a parent to a new context.

**Comment by tomas-langer** [comment]
Can you please try the test with `-Djava.security.egd=file:/dev/urandom`?
There is a known problem with systems with low entropy to generate random numbers. It may be this problem rather than a contention. 
We can remove the existing code for 2.0 (when we get rid of `ContextualRegistry` in WebServer and replace it with `Context`).
